// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlanningBet.Insights.API.Infra.Context;

#nullable disable

namespace PlanningBet.Insights.API.Migrations
{
    [DbContext(typeof(InsightsDbContext))]
    [Migration("20230809121416_AddInsights")]
    partial class AddInsights
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlanningBet.Insights.API.Models.InsightEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Insights");

                    b.HasData(
                        new
                        {
                            Id = new Guid("218a5026-efda-4700-9d31-3e538f8cb736"),
                            Active = true,
                            Name = "Vitórias",
                            Type = "sequency",
                            Value = "wins"
                        },
                        new
                        {
                            Id = new Guid("8b36e232-2cb4-40df-bcff-5af4706e5b11"),
                            Active = true,
                            Name = "Derrotas",
                            Type = "sequency",
                            Value = "loses"
                        },
                        new
                        {
                            Id = new Guid("4629a74b-3133-44a6-9267-3d9e77ae7f7e"),
                            Active = true,
                            Name = "Invencibilidade",
                            Type = "sequency",
                            Value = "invincibility"
                        },
                        new
                        {
                            Id = new Guid("d4d9e01f-506a-4b96-ae81-43f32188fc0a"),
                            Active = true,
                            Name = "Marcou gols",
                            Type = "sequency",
                            Value = "scored"
                        },
                        new
                        {
                            Id = new Guid("b359a0df-a478-4fe6-8fa9-4afe28e398e5"),
                            Active = true,
                            Name = "Sofreu gols",
                            Type = "sequency",
                            Value = "conceded"
                        },
                        new
                        {
                            Id = new Guid("8423bdeb-e862-4e7b-9805-34dcd005b4d3"),
                            Active = true,
                            Name = "Ambas marcam",
                            Type = "sequency",
                            Value = "bttsYes"
                        },
                        new
                        {
                            Id = new Guid("09deedad-cd4e-4f27-89f6-9adcdbe48871"),
                            Active = false,
                            Name = "Ambas marcam Não",
                            Type = "sequency",
                            Value = "bttsNo"
                        },
                        new
                        {
                            Id = new Guid("d9e1039f-5a5f-409b-aea1-76ea368df5f5"),
                            Active = true,
                            Name = "Over 2.5",
                            Type = "sequency",
                            Value = "over25"
                        },
                        new
                        {
                            Id = new Guid("55db23d6-4933-4ca3-b438-50f3a7659696"),
                            Active = false,
                            Name = "Under 2.5",
                            Type = "sequency",
                            Value = "under25"
                        },
                        new
                        {
                            Id = new Guid("39c089dd-607e-4e32-bedc-f32aab68d39a"),
                            Active = true,
                            Name = "Cantos",
                            Type = "sequency",
                            Value = "corner"
                        },
                        new
                        {
                            Id = new Guid("4e589feb-f99b-4c7e-82f9-2300cd31ef41"),
                            Active = true,
                            Name = "Cartões",
                            Type = "sequency",
                            Value = "cards"
                        },
                        new
                        {
                            Id = new Guid("7e9f65bc-ccae-4251-ad11-ae5222b31992"),
                            Active = true,
                            Name = "Pontos por jogo",
                            Type = "comparativeHomeAway",
                            Value = "ppg"
                        },
                        new
                        {
                            Id = new Guid("2e29ffc5-ae13-40d8-83b1-f5688396659e"),
                            Active = true,
                            Name = "% de vitórias",
                            Type = "comparativeHomeAway",
                            Value = "winsPercentage"
                        },
                        new
                        {
                            Id = new Guid("87cf2cb9-6d33-4508-8d28-fa8ef6db5ea5"),
                            Active = true,
                            Name = "Primeiro a marcar",
                            Type = "comparativeHomeAway",
                            Value = "firstToScore"
                        },
                        new
                        {
                            Id = new Guid("aa4cc52e-c2a6-4c97-992c-14bf9a63beef"),
                            Active = true,
                            Name = "Gols marcados",
                            Type = "comparativeHomeAway",
                            Value = "scoredHomeAway"
                        },
                        new
                        {
                            Id = new Guid("6e9bf393-3ed2-46f5-8a64-70c54d22012b"),
                            Active = true,
                            Name = "Gols sofridos",
                            Type = "comparativeHomeAway",
                            Value = "concededHomeAway"
                        },
                        new
                        {
                            Id = new Guid("18984508-7725-4433-a14c-95188032db48"),
                            Active = true,
                            Name = "Finalizações",
                            Type = "comparativeHomeAway",
                            Value = "shots"
                        },
                        new
                        {
                            Id = new Guid("576517e3-bbf6-4a72-a992-5317c5f7cc00"),
                            Active = true,
                            Name = "xG a favor",
                            Type = "comparativeHomeAway",
                            Value = "favorXG"
                        },
                        new
                        {
                            Id = new Guid("16f808ae-0fdb-4fbe-81d8-068a2bbd08df"),
                            Active = false,
                            Name = "xG contra",
                            Type = "comparativeHomeAway",
                            Value = "concededXG"
                        },
                        new
                        {
                            Id = new Guid("e9327cef-4be9-4030-aef9-1a162d34d435"),
                            Active = true,
                            Name = "Gols marcados no primeiro tempo",
                            Type = "comparativeGoals",
                            Value = "goalsScoredFirstHalf"
                        },
                        new
                        {
                            Id = new Guid("0df6f7b2-2f2b-46f6-92f4-db7567116413"),
                            Active = true,
                            Name = "Gols sofridos no primeiro tempo",
                            Type = "comparativeGoals",
                            Value = "goalsConcededFirstHalf"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
